### ISSUE TITLE
agent connect dataproxy fail when using docker-compose

### ISSUE THREAD

**Issue by LeBW** [apache/incubator-inlong#1453]
#### Expected behavior

agent should send message to dataproxy when detect change.

#### Actual behavior

the agent and the dataproxy fails to communicate.

#### Steps to reproduce

1. deploy inlong using `docker-compose`
2. new a business in `inlong-web`.
3. create `.inlong` dir in agent and `bid.local` to indicate dataproxy address. 
4. send a HTTP request to the agent to add a trigger.
5. add a line in the target file in the agent.
6. then we can see the error in `agent` and `dataproxy`.

Here is the error in agent
```
2021-08-22 09:40:03,620 INFO [task-running-thread-1] (network.ClientMgr@getRealHosts:863): host=dataproxy:46801{dataproxy:46801}
2021-08-22 09:40:03,654 INFO [New I/O worker #1] (network.NettyClient$1@operationComplete:80): connect ack! dataproxy
2021-08-22 09:40:03,654 INFO [task-running-thread-1] (network.NettyClient@connect:101): ip dataproxy stat READY
2021-08-22 09:40:03,655 INFO [task-running-thread-1] (network.ClientMgr@initConnection:247): build a connection success! dataproxy,channel [id: 0x3918d4d4, /172.19.0.8:52672 => dataproxy/172.19.0.6:46801]
2021-08-22 09:40:03,655 INFO [task-running-thread-1] (network.ClientMgr@initConnection:251): client map size 1,client list size 1
2021-08-22 09:40:03,655 INFO [task-running-thread-1] (network.ClientMgr@setProxyInfoList:844): update all connection ,client map size 1,client list size 1
2021-08-22 09:40:03,656 INFO [proxyConfigManager] (config.ProxyConfigManager@compareProxyList:295): ProxyConfigEntry [hostMap={dataproxy:46801=dataproxy:46801{dataproxy:46801}}, load=0, bsn=0, tsnMap={}, size=1, isInterVisit=true, bid=libw_test_1, switch=0]
2021-08-22 09:40:03,656 INFO [SendHBThread] (network.ClientMgr@removeBadRealClient:664): this host dataproxy is active! so keep it
2021-08-22 09:40:03,657 INFO [SendHBThread] (network.ClientMgr@replaceBadConnectionHB:727): hasn't bad host! so keep it
2021-08-22 09:40:03,657 INFO [proxyConfigManager] (config.ProxyConfigManager@compareProxyList:329): proxy IP list doesn't change, load 0
2021-08-22 09:40:03,657 INFO [proxyConfigManager] (config.ProxyConfigManager@run:121): ProxyConf update!
2021-08-22 09:40:03,657 INFO [proxyConfigManager] (config.ProxyConfigManager@run:136): sleep time 334
2021-08-22 09:40:03,659 INFO [TimeoutScanThread] (threads.TimeoutScanThread@run:159): TimeoutScanThread Thread=91 started !
2021-08-22 09:40:03,660 INFO [task-running-thread-1] (network.Sender@<init>:102): proxy sdk is starting!
2021-08-22 09:40:03,661 INFO [MetricWorkerThread] (threads.MetricWorkerThread@run:192): MetricWorkerThread Thread=92 started !
2021-08-22 09:40:03,661 INFO [IndexCollectThread] (threads.IndexCollectThread@run:51): IndexCollectThread Thread=93 started !
2021-08-22 09:40:03,662 INFO [ManagerFetcherThread] (threads.ManagerFetcherThread@run:50): ManagerFetcherThread Thread=94 started !
2021-08-22 09:40:03,662 INFO [task-running-thread-1] (reader.TextFileReader@init:140): file name for task is /data/collect-data/test.log, md5 is 4e45ffd9c5236830dc220412764c9d12
2021-08-22 09:40:03,671 INFO [ManagerFetcherThread] (utils.ServiceDiscoveryUtils@getManagerIpListByHttp:159): Begin to get configure from manager http://manager:8083/api/getmanagervirtualip, param is [operation=query, username=]
2021-08-22 09:40:03,745 ERROR [ManagerFetcherThread] (utils.ServiceDiscoveryUtils@getManagerIpList:85): ServiceDiscovery get managerIpList from managerHost occur error, will try to get from managerIpList.
2021-08-22 09:40:03,745 ERROR [ManagerFetcherThread] (utils.ServiceDiscoveryUtils@getManagerIpList:104): ServiceDiscovery managerIp is null, lastestManagerIPList is [].
2021-08-22 09:40:03,746 INFO [ManagerFetcherThread] (utils.ServiceDiscoveryUtils@getLocalManagerIpList:226): ServiceDiscovery start loading config for :/opt/inlong-agent/.inlong/.managerIps from file ...
2021-08-22 09:40:03,746 INFO [ManagerFetcherThread] (utils.ServiceDiscoveryUtils@getLocalManagerIpList:232): ServiceDiscovery no found local bidInfo file, doesn't matter, path is [/opt/inlong-agent/.inlong/.managerIps].
2021-08-22 09:40:03,746 ERROR [ManagerFetcherThread] (utils.ServiceDiscoveryUtils@getManagerIpList:146): ServiceDiscovery get empty TdmIpList from local file, file path is [/opt/inlong-agent/.inlong/.managerIps].
2021-08-22 09:40:03,746 ERROR [ManagerFetcherThread] (threads.ManagerFetcherThread@run:55): ManagerFetcher get managerIpList is blank.
2021-08-22 09:40:04,659 INFO [TimeoutScanThread] (threads.TimeoutScanThread@run:180): TimeoutScanThread thread=91's currentBufferSize = 0
2021-08-22 09:40:09,592 INFO [ProxySink-running-thread-1] (sinks.ProxySink@lambda$null$1:130): send bid libw_test_1 with message size 6, the job id is job_1629625203_1_1, read file is /data/collect-data/test.logdataTime is 1629625203542
2021-08-22 09:40:09,594 ERROR [New I/O worker #1] (network.ClientHandler@exceptionCaught:63): this channel [id: 0x3918d4d4, /172.19.0.8:52672 => dataproxy/172.19.0.6:46801] has error! , reason is {} 
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:229)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:44)
	at org.apache.inlong.dataproxy.codec.ProtocolEncoder.processCompress(ProtocolEncoder.java:409)
	at org.apache.inlong.dataproxy.codec.ProtocolEncoder.constructBody(ProtocolEncoder.java:122)
	at org.apache.inlong.dataproxy.codec.ProtocolEncoder.writeToBuf7(ProtocolEncoder.java:235)
	at org.apache.inlong.dataproxy.codec.ProtocolEncoder.encode(ProtocolEncoder.java:64)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at org.jboss.netty.channel.Channels.write(Channels.java:704)
	at org.jboss.netty.channel.Channels.write(Channels.java:671)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
	at org.apache.inlong.dataproxy.network.NettyClient.write(NettyClient.java:175)
	at org.apache.inlong.dataproxy.network.Sender.asyncSendMessage(Sender.java:569)
	at org.apache.inlong.dataproxy.DefaultMessageSender.asyncSendMessage(DefaultMessageSender.java:415)
	at org.apache.inlong.agent.plugin.sinks.SenderManager.sendBatch(SenderManager.java:222)
	at org.apache.inlong.agent.plugin.sinks.ProxySink.lambda$null$1(ProxySink.java:128)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.inlong.agent.plugin.sinks.ProxySink.lambda$flushCache$2(ProxySink.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-08-22 09:40:09,596 INFO [New I/O worker #1] (network.ClientMgr@setConnectionFrozen:287): set this channel [id: 0x3918d4d4, /172.19.0.8:52672 => dataproxy/172.19.0.6:46801] frozen
2021-08-22 09:40:09,596 INFO [New I/O worker #1] (network.ClientMgr@setConnectionFrozen:296): end to froze this channel [id: 0x3918d4d4, /172.19.0.8:52672 => dataproxy/172.19.0.6:46801]
2021-08-22 09:40:18,455 INFO [AbstractDaemon-running-thread-7] (utils.HttpManager@doSentPost:80): request url http://manager:8083/api/inlong/manager/openapi/agent/file_agent/taskconf, dto: TaskRequsetDto(agentIp=172.19.0.8, commandInfo=[]), return str {"success":true,"errMsg":null,"data":{"cmdConfigs":[],"dataConfigs":[]}}
2021-08-22 09:40:18,456 INFO [AbstractDaemon-running-thread-7] (fetcher.ManagerFetcher@dealWithFetchResult:193): deal with fetch result TaskResult(cmdConfigs=[], dataConfigs=[])
2021-08-22 09:40:20,657 INFO [SendHBThread] (network.ClientMgr@removeBadRealClient:661): this host dataproxy is bad! so remove it
2021-08-22 09:40:20,658 INFO [SendHBThread] (network.Sender@waitForAckForChannel:655): wait for ack for channel [id: 0x3918d4d4, /172.19.0.8:52672 => dataproxy/172.19.0.6:46801]
2021-08-22 09:40:24,662 INFO [TimeoutScanThread] (threads.TimeoutScanThread@run:180): TimeoutScanThread thread=91's currentBufferSize = 1
2021-08-22 09:40:29,666 WARN [TimeoutScanThread] (sinks.SenderManager$AgentSenderCallback@onMessageAck:192): send bid libw_test_1, tid stream_1, jobId job_1629625203_1_1, dataTime 1629625203542 fail with times 0
2021-08-22 09:40:29,668 ERROR [TimeoutScanThread] (sinks.SenderManager@sendBatch:231): Exception caught
org.apache.inlong.dataproxy.network.ProxysdkException: NO_CONNECTION
	at org.apache.inlong.dataproxy.network.Sender.asyncSendMessage(Sender.java:507)
	at org.apache.inlong.dataproxy.DefaultMessageSender.asyncSendMessage(DefaultMessageSender.java:415)
	at org.apache.inlong.agent.plugin.sinks.SenderManager.sendBatch(SenderManager.java:222)
	at org.apache.inlong.agent.plugin.sinks.SenderManager$AgentSenderCallback.onMessageAck(SenderManager.java:194)
	at org.apache.inlong.dataproxy.threads.TimeoutScanThread.checkMessageIdBasedCallbacks(TimeoutScanThread.java:148)
	at org.apache.inlong.dataproxy.threads.TimeoutScanThread.run(TimeoutScanThread.java:168)
```

Here is the error in dataproxy
```
2021-08-23 02:02:19,354 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x5b1ab805, /172.19.0.8:42506 :> /172.19.0.6:46801]
2021-08-23 02:02:42,350 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:03:05,356 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x3f147d3c, /172.19.0.8:42702 :> /172.19.0.6:46801]
2021-08-23 02:03:42,357 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:04:04,361 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x36049fd1, /172.19.0.8:42890 :> /172.19.0.6:46801]
2021-08-23 02:04:09,976 INFO config.ConfigManager$ReloadConfigWorker (ConfigManager.java:checkWithManager:257): start to request http://manager:8083/api/inlong/manager/openapi/dataproxy/getConfig to get config info
2021-08-23 02:04:09,985 ERROR holder.PropertiesConfigHolder (PropertiesConfigHolder.java:loadFromHolderToFile:113): error in writing file
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at org.apache.inlong.dataproxy.config.holder.PropertiesConfigHolder.loadFromHolderToFile(PropertiesConfigHolder.java:95)
	at org.apache.inlong.dataproxy.config.ConfigManager.updatePropertiesHolder(ConfigManager.java:130)
	at org.apache.inlong.dataproxy.config.ConfigManager.addMxProperties(ConfigManager.java:149)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkWithManager(ConfigManager.java:275)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:296)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:316)
2021-08-23 02:04:09,986 ERROR holder.PropertiesConfigHolder (PropertiesConfigHolder.java:loadFromHolderToFile:113): error in writing file
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at org.apache.inlong.dataproxy.config.holder.PropertiesConfigHolder.loadFromHolderToFile(PropertiesConfigHolder.java:95)
	at org.apache.inlong.dataproxy.config.ConfigManager.updatePropertiesHolder(ConfigManager.java:130)
	at org.apache.inlong.dataproxy.config.ConfigManager.addTopicProperties(ConfigManager.java:137)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkWithManager(ConfigManager.java:276)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:296)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:316)
2021-08-23 02:04:23,361 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:04:44,365 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0xf882eb59, /172.19.0.8:43020 :> /172.19.0.6:46801]
2021-08-23 02:05:15,366 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:05:46,370 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x87bdf5d5, /172.19.0.8:43184 :> /172.19.0.6:46801]
2021-08-23 02:06:03,370 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:06:40,373 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0xd5e8f552, /172.19.0.8:43340 :> /172.19.0.6:46801]
2021-08-23 02:06:57,374 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:07:34,386 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x53e5fa66, /172.19.0.8:43516 :> /172.19.0.6:46801]
2021-08-23 02:08:05,382 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:08:36,387 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0xf512512d, /172.19.0.8:43724 :> /172.19.0.6:46801]
2021-08-23 02:08:53,388 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:09:15,393 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x1709cc23, /172.19.0.8:43874 :> /172.19.0.6:46801]
2021-08-23 02:09:46,397 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:10:09,403 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x81d09a11, /172.19.0.8:44042 :> /172.19.0.6:46801]
2021-08-23 02:10:17,317 INFO config.ConfigManager$ReloadConfigWorker (ConfigManager.java:checkWithManager:257): start to request http://manager:8083/api/inlong/manager/openapi/dataproxy/getConfig to get config info
2021-08-23 02:10:17,335 ERROR holder.PropertiesConfigHolder (PropertiesConfigHolder.java:loadFromHolderToFile:113): error in writing file
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at org.apache.inlong.dataproxy.config.holder.PropertiesConfigHolder.loadFromHolderToFile(PropertiesConfigHolder.java:95)
	at org.apache.inlong.dataproxy.config.ConfigManager.updatePropertiesHolder(ConfigManager.java:130)
	at org.apache.inlong.dataproxy.config.ConfigManager.addMxProperties(ConfigManager.java:149)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkWithManager(ConfigManager.java:275)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:296)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:316)
2021-08-23 02:10:17,335 ERROR holder.PropertiesConfigHolder (PropertiesConfigHolder.java:loadFromHolderToFile:113): error in writing file
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at org.apache.inlong.dataproxy.config.holder.PropertiesConfigHolder.loadFromHolderToFile(PropertiesConfigHolder.java:95)
	at org.apache.inlong.dataproxy.config.ConfigManager.updatePropertiesHolder(ConfigManager.java:130)
	at org.apache.inlong.dataproxy.config.ConfigManager.addTopicProperties(ConfigManager.java:137)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkWithManager(ConfigManager.java:276)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:296)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:316)
2021-08-23 02:10:32,403 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:10:53,409 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x894320b0, /172.19.0.8:44186 :> /172.19.0.6:46801]
2021-08-23 02:11:30,411 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:12:01,417 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x7053237b, /172.19.0.8:44372 :> /172.19.0.6:46801]
2021-08-23 02:12:38,418 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:13:01,422 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x23055382, /172.19.0.8:44588 :> /172.19.0.6:46801]
2021-08-23 02:13:24,424 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:13:47,430 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x9c38b7af, /172.19.0.8:44724 :> /172.19.0.6:46801]
2021-08-23 02:14:10,432 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:14:31,436 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x50a86ba4, /172.19.0.8:44874 :> /172.19.0.6:46801]
2021-08-23 02:14:54,438 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:15:25,443 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x95f33435, /172.19.0.8:45014 :> /172.19.0.6:46801]
2021-08-23 02:15:42,443 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:16:19,448 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x6ee4279c, /172.19.0.8:45160 :> /172.19.0.6:46801]
2021-08-23 02:16:30,101 INFO config.ConfigManager$ReloadConfigWorker (ConfigManager.java:checkWithManager:257): start to request http://manager:8083/api/inlong/manager/openapi/dataproxy/getConfig to get config info
2021-08-23 02:16:30,120 ERROR holder.PropertiesConfigHolder (PropertiesConfigHolder.java:loadFromHolderToFile:113): error in writing file
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at org.apache.inlong.dataproxy.config.holder.PropertiesConfigHolder.loadFromHolderToFile(PropertiesConfigHolder.java:95)
	at org.apache.inlong.dataproxy.config.ConfigManager.updatePropertiesHolder(ConfigManager.java:130)
	at org.apache.inlong.dataproxy.config.ConfigManager.addMxProperties(ConfigManager.java:149)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkWithManager(ConfigManager.java:275)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:296)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:316)
2021-08-23 02:16:30,121 ERROR holder.PropertiesConfigHolder (PropertiesConfigHolder.java:loadFromHolderToFile:113): error in writing file
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at org.apache.inlong.dataproxy.config.holder.PropertiesConfigHolder.loadFromHolderToFile(PropertiesConfigHolder.java:95)
	at org.apache.inlong.dataproxy.config.ConfigManager.updatePropertiesHolder(ConfigManager.java:130)
	at org.apache.inlong.dataproxy.config.ConfigManager.addTopicProperties(ConfigManager.java:137)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkWithManager(ConfigManager.java:276)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:296)
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:316)
2021-08-23 02:16:38,451 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:17:00,457 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0xe84b685a, /172.19.0.8:45342 :> /172.19.0.6:46801]
2021-08-23 02:17:17,459 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:17:54,464 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x125ad6da, /172.19.0.8:45458 :> /172.19.0.6:46801]
2021-08-23 02:18:13,464 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:18:35,469 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0xce948d0b, /172.19.0.8:45640 :> /172.19.0.6:46801]
2021-08-23 02:18:58,468 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:19:21,478 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x1e06da56, /172.19.0.8:45780 :> /172.19.0.6:46801]
2021-08-23 02:19:44,472 INFO source.ServerMessageHandler (ServerMessageHandler.java:channelOpen:214): connections=0,maxConnections=5000
2021-08-23 02:20:05,475 ERROR source.ServerMessageHandler (ServerMessageHandler.java:channelClosed:643): channel closed [id: 0x42c2f28d, /172.19.0.8:45930 :> /172.19.0.6:46801]

```

#### System configuration
**InLong version**: x.y

**Comment by dockerzhang** [comment]
@EMsnap PTAL
