### ISSUE TITLE
[Bug] Some resultType is wrong in mapper

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-inlong#1604]
### What happened

Cannot start InLong manager module, due to ClassNotFoundException.

e.g. `org.apache.inlong.manager.common.pojo.dataproxy.DataProxyConfig` need to change to `org.apache.inlong.manager.dao.entity.DataProxyConfig`
https://github.com/apache/incubator-inlong/blob/73d149610e1d88913a65529a5bb003bf1ea058a7/inlong-manager/manager-dao/src/main/resources/mappers/BusinessEntityMapper.xml#L100-L107

### What you expected to happen

```java
Caused by: org.apache.ibatis.type.TypeException: Could not resolve type alias 'org.apache.inlong.manager.common.pojo.dataproxy.DataProxyConfig'.  Cause: java.lang.ClassNotFoundException: Cannot find class: org.apache.inlong.manager.common.pojo.dataproxy.DataProxyConfig
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:120)
	at org.apache.ibatis.builder.BaseBuilder.resolveAlias(BaseBuilder.java:149)
	at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:116)
	... 123 common frames omitted
Caused by: java.lang.ClassNotFoundException: Cannot find class: org.apache.inlong.manager.common.pojo.dataproxy.DataProxyConfig
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:196)
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:89)
	at org.apache.ibatis.io.Resources.classForName(Resources.java:261)
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:116)
	... 125 common frames omitted
```

### How to reproduce

Start InLongWebApplication

### InLong version

0.10.0 RC1

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
This issue is in master branch, we also need to add `masrer` version in the `bug-report.yml`

**Comment by dockerzhang** [comment]
> This issue is in master branch, we also need to add `masrer` version in the `bug-report.yml`

@shink PTAL
