### ISSUE TITLE
[Bug]Create multiple file import tasks, and inlong-agent reports an error when registering metric

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#1978]
### What happened

For the same data access service, create multiple data streams, and each data stream is configured with file import tasks,
the inlong-agent reports the error as follows:

`2021-12-14 11:40:42,640 ERROR [job-running-thread-5] (metrics.MetricRegister@register:53): org.apache.inlong:type=SinkMetric,tagName=AgentProxySinkMetric
javax.management.InstanceAlreadyExistsException: org.apache.inlong:type=SinkMetric,tagName=AgentProxySinkMetric
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.inlong.commons.config.metrics.MetricRegister.register(MetricRegister.java:50)
        at org.apache.inlong.agent.plugin.metrics.SinkJmxMetric.<init>(SinkJmxMetric.java:44)
        at org.apache.inlong.agent.plugin.sinks.ProxySink.<init>(ProxySink.java:101)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.apache.inlong.agent.core.job.Job.createTasks(Job.java:88)
        at org.apache.inlong.agent.core.job.JobWrapper.submitAllTasks(JobWrapper.java:84)
        at org.apache.inlong.agent.core.job.JobWrapper.run(JobWrapper.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

### What you expected to happen

Multiple import tasks run normally

### How to reproduce

Create multiple data streams for the same data access service, and each data stream is configured with file import tasks

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
leave it to me
