### ISSUE TITLE
[Bug][Agent] Update guava version

### ISSUE THREAD

**Issue by EMsnap** [apache/incubator-inlong#3050]
### What happened

[Bug] Agent update guava version to 30

when connect to mysql

2022-03-10 16:05:58.702 -ERROR  [pool-9-thread-1] o.a.i.a.p.s.r.BinlogReader     : binlog job with jobConf 3 has error Unable to initialize and start connector's task class 'io.debezium.connector.mysql.MySqlConnectorTask' with config: {snapshot.mode=initial, database.allowPublicKeyRetrieval=true, database.user=root, offset.flush.interval.ms=500, database.password=********, offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore, database.server.name=3, database.serverTimezone=UTC, table.whitelist=apache_inlong_manager.stream_sink_field, value.converter.schemas.enable=false, include.schema.changes=false, offset.storage.file.filename=/opt/inlong-agent/.history/offset.dat3, connector.class=io.debezium.connector.mysql.MySqlConnector, database.port=3306, database.history.file.filename=/opt/inlong-agent/.history/history.dat3, key.converter.schemas.enable=false, database.snapshot.mode=initial, database.history.store.only.monitored.tables.ddl=false, tombstones.on.delete=false, database.hostname=172.17.198.203, database.history=io.debezium.relational.history.FileDatabaseHistory, database.whitelist=, name=engine3}
java.lang.NoClassDefFoundError: com/google/common/collect/RangeSet
        at io.debezium.connector.mysql.GtidSet.lambda$new$0(GtidSet.java:51) ~[debezium-connector-mysql-1.8.1.Final.jar:1.8.1.Final]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[?:1.8.0_322]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_322]
        at io.debezium.connector.mysql.GtidSet.<init>(GtidSet.java:50) ~[debezium-connector-mysql-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.connector.mysql.MySqlHistoryRecordComparator.isPositionAtOrBefore(MySqlHistoryRecordComparator.java:48) ~[debezium-connector-mysql-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.history.HistoryRecordComparator.isAtOrBefore(HistoryRecordComparator.java:52) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.history.AbstractDatabaseHistory.lambda$recover$2(AbstractDatabaseHistory.java:115) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.history.FileDatabaseHistory.lambda$recoverRecords$2(FileDatabaseHistory.java:147) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.util.FunctionalReadWriteLock.write(FunctionalReadWriteLock.java:99) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.history.FileDatabaseHistory.recoverRecords(FileDatabaseHistory.java:142) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.history.AbstractDatabaseHistory.recover(AbstractDatabaseHistory.java:112) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.history.DatabaseHistory.recover(DatabaseHistory.java:158) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:62) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.schema.HistorizedDatabaseSchema.recover(HistorizedDatabaseSchema.java:38) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.connector.mysql.MySqlConnectorTask.validateAndLoadDatabaseHistory(MySqlConnectorTask.java:369) ~[debezium-connector-mysql-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:108) ~[debezium-connector-mysql-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130) ~[debezium-core-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759) [debezium-embedded-1.8.1.Final.jar:1.8.1.Final]
        at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188) [debezium-embedded-1.8.1.Final.jar:1.8.1.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.RangeSet
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_322]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_322]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_322]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_322]
        ... 22 more

### What you expected to happen

[Bug] Agent update guava version to 30

### How to reproduce

[Bug] Agent update guava version to 30

### Environment

[Bug] Agent update guava version

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3051.
