### ISSUE TITLE
[Bug][Sort] Start sort task failed as parsing the config error

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3054]
### What happened

The error log in Flink Job Manager:
```
2022-03-11 02:00:31,860 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: Pulsar source (1/1)#661 (c71c4057ed239170759f4775fa43c6bb) switched from INITIALIZING to FAILED with failure cause: org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.inlong.sort.protocol.transformation.TransformationRule` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (byte[])"{"id":3,"source_info":{"type":"pulsar","admin_url":"http://127.0.0.1:8080","service_url":"pulsar://127.0.0.1:6650","topic":"persistent://public/b_test_group/test_stream","subscription_name":"inlong_app_test_stream_consumer_group","deserialization_info":{"type":"json"},"fields":[{"type":"base","name":"dt","format_info":{"type":"timestamp","format":"MILLIS"}},{"type":"base","name":"age","format_info":{"type":"int"}},{"type":"base","name":"name","format_info":{"type":"string"}}],"authentica"[truncated 957 bytes]; line: 1, column: 1131] (through reference chain: org.apache.inlong.sort.protocol.DataFlowInfo["transformation_info"]->org.apache.inlong.sort.protocol.transformation.TransformationInfo["transform_rule"])
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	...
	at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
	at org.apache.inlong.sort.meta.zookeeper.ZookeeperMetaWatcher$DataFlowsChildrenWatcherListener.getDataFlowInfo(ZookeeperMetaWatcher.java:158)
	at org.apache.inlong.sort.meta.zookeeper.ZookeeperMetaWatcher$DataFlowsChildrenWatcherListener.onChildAdded(ZookeeperMetaWatcher.java:107)
	at org.apache.inlong.sort.meta.zookeeper.ZookeeperMetaWatcher$DataFlowsChildrenWatcherListener.onInitialized(ZookeeperMetaWatcher.java:149)
	at org.apache.inlong.sort.meta.zookeeper.ZookeeperWatcherUtils.open(ZookeeperWatcherUtils.java:94)
	at org.apache.inlong.sort.meta.zookeeper.ZookeeperMetaWatcher.open(ZookeeperMetaWatcher.java:60)
	at org.apache.inlong.sort.meta.MetaManager.open(MetaManager.java:100)
	at org.apache.inlong.sort.meta.MetaManager.getInstance(MetaManager.java:66)
	at org.apache.inlong.sort.flink.multitenant.pulsar.MultiTopicPulsarSourceFunction.open(MultiTopicPulsarSourceFunction.java:66)
```

### What you expected to happen

The Sort task should be started successfully.

### How to reproduce

Push Hive sink info to ZooKeeper and start the Sort job, you'll see the above error.

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/incubator-inlong/pull/3056.
