### ISSUE TITLE
[Bug][Manager] Save stream sink field error

### ISSUE THREAD

**Issue by healchow** [apache/incubator-inlong#3134]
### What happened

Error log:

```
2022-03-14 14:13:36.004 [http-nio-8083-exec-3] ERROR o.a.i.m.web.config.ControllerExceptionHandler:124 - Failed to handle request on path:/api/inlong/manager/sink/save, user:admin
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'isSourceMetaField' not found. Available parameters are [list, param1]
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
        at com.sun.proxy.$Proxy88.insert(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
```

### What you expected to happen

Should save stream sink field successfully.

### How to reproduce

Save the stream sink field list.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I will fix this issue.
