### ISSUE TITLE
[Bug][Manager] ConsumptionMqExtBase cannot be cast to ConsumptionPulsarInfo

### ISSUE THREAD

**Issue by xuesongxs** [apache/incubator-inlong#3242]
### What happened
Submit NewConsume failed!

![image](https://user-images.githubusercontent.com/54351417/159111998-08a2890f-e28a-4438-8ef8-b3d28f247dfb.png)

```
2022-03-18 20:09:50.489 [http-nio-8083-exec-6] ERROR o.a.i.m.web.config.ControllerExceptionHandler:124 - Failed to handle request on path:/api/inlong/manager/consumption/save, user:admin
java.lang.ClassCastException: org.apache.inlong.manager.common.pojo.consumption.ConsumptionMqExtBase cannot be cast to org.apache.inlong.manager.common.pojo.consumption.ConsumptionPulsarInfo
        at org.apache.inlong.manager.service.core.impl.ConsumptionServiceImpl.savePulsarInfo(ConsumptionServiceImpl.java:167)
        at org.apache.inlong.manager.service.core.impl.ConsumptionServiceImpl.save(ConsumptionServiceImpl.java:156)
        at org.apache.inlong.manager.service.core.impl.ConsumptionServiceImpl$$FastClassBySpringCGLIB$$91c8c7ca.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at org.apache.inlong.manager.service.core.impl.ConsumptionServiceImpl$$EnhancerBySpringCGLIB$$4401f9d9.save(<generated>)
        at org.apache.inlong.manager.web.controller.ConsumptionController.save(ConsumptionController.java:90)
        at org.apache.inlong.manager.web.controller.ConsumptionController$$FastClassBySpringCGLIB$$c7e6cdf7.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.apache.inlong.manager.service.core.operationlog.OperationLogRecorder.doAround(OperationLogRecorder.java:72)
        at org.apache.inlong.manager.web.aspect.LogAspect.doAround(LogAspect.java:41)
        at sun.reflect.GeneratedMethodAccessor337.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
```

### What you expected to happen

Submit NewConsume sucessful.

### How to reproduce

1、Data Consumption/NewConsume
2、Submit

### Environment

CentOS 7.2

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@healchow PTAL, thanks.

**Comment by xuesongxs** [comment]
> @healchow PTAL, thanks.
Is it convenient to add a wechat to ask questions?

**Comment by healchow** [comment]
> > @healchow PTAL, thanks.
> > Is it convenient to add a wechat to ask questions?

yes, my wechat id is `ma_shoufeng`.
